[package]
name = "lsert"
version = "0.1.0"
edition = "2021"

[dependencies]
redis = { version = "0.23.0", features = ["json"] }
serde_json = "1.0.94"
tiny_http = "0.12.0"
xml-rs = "0.8.4"

[features]
db_collab = []
